//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson_3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingMessage
    {
        public int MailingNumber { get; set; }
        public string Writing { get; set; }
        public int Recipient { get; set; }
        public System.DateTime DateSending { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual Messeage Messeage { get; set; }
    }
}
